/*
 * This source file was generated by the Gradle 'init' task
 */
package com.banaanae.javasccore;

public class JavaSCCore {
    public static void main(String[] args) {
        System.out.println("Start starting");
    }
}
